export interface WechatEmoji {
  name: string;
  token: string;
  src: string;
}

// Keep the upstream Web WeChat display order and names.
export const wechatEmojis: readonly WechatEmoji[] = [
  { name: "微笑", token: "[微笑]", src: "/images/wechat-emoji/001.webp" },
  { name: "撇嘴", token: "[撇嘴]", src: "/images/wechat-emoji/002.webp" },
  { name: "色", token: "[色]", src: "/images/wechat-emoji/003.webp" },
  { name: "发呆", token: "[发呆]", src: "/images/wechat-emoji/004.webp" },
  { name: "得意", token: "[得意]", src: "/images/wechat-emoji/005.webp" },
  { name: "流泪", token: "[流泪]", src: "/images/wechat-emoji/006.webp" },
  { name: "害羞", token: "[害羞]", src: "/images/wechat-emoji/007.webp" },
  { name: "闭嘴", token: "[闭嘴]", src: "/images/wechat-emoji/008.webp" },
  { name: "睡", token: "[睡]", src: "/images/wechat-emoji/009.webp" },
  { name: "大哭", token: "[大哭]", src: "/images/wechat-emoji/010.webp" },
  { name: "尴尬", token: "[尴尬]", src: "/images/wechat-emoji/011.webp" },
  { name: "发怒", token: "[发怒]", src: "/images/wechat-emoji/012.webp" },
  { name: "调皮", token: "[调皮]", src: "/images/wechat-emoji/013.webp" },
  { name: "呲牙", token: "[呲牙]", src: "/images/wechat-emoji/014.webp" },
  { name: "惊讶", token: "[惊讶]", src: "/images/wechat-emoji/015.webp" },
  { name: "难过", token: "[难过]", src: "/images/wechat-emoji/016.webp" },
  { name: "囧", token: "[囧]", src: "/images/wechat-emoji/017.webp" },
  { name: "抓狂", token: "[抓狂]", src: "/images/wechat-emoji/018.webp" },
  { name: "吐", token: "[吐]", src: "/images/wechat-emoji/019.webp" },
  { name: "偷笑", token: "[偷笑]", src: "/images/wechat-emoji/020.webp" },
  { name: "愉快", token: "[愉快]", src: "/images/wechat-emoji/021.webp" },
  { name: "白眼", token: "[白眼]", src: "/images/wechat-emoji/022.webp" },
  { name: "傲慢", token: "[傲慢]", src: "/images/wechat-emoji/023.webp" },
  { name: "困", token: "[困]", src: "/images/wechat-emoji/024.webp" },
  { name: "惊恐", token: "[惊恐]", src: "/images/wechat-emoji/025.webp" },
  { name: "憨笑", token: "[憨笑]", src: "/images/wechat-emoji/026.webp" },
  { name: "悠闲", token: "[悠闲]", src: "/images/wechat-emoji/027.webp" },
  { name: "咒骂", token: "[咒骂]", src: "/images/wechat-emoji/028.webp" },
  { name: "疑问", token: "[疑问]", src: "/images/wechat-emoji/029.webp" },
  { name: "嘘", token: "[嘘]", src: "/images/wechat-emoji/030.webp" },
  { name: "晕", token: "[晕]", src: "/images/wechat-emoji/031.webp" },
  { name: "衰", token: "[衰]", src: "/images/wechat-emoji/032.webp" },
  { name: "骷髅", token: "[骷髅]", src: "/images/wechat-emoji/033.webp" },
  { name: "敲打", token: "[敲打]", src: "/images/wechat-emoji/034.webp" },
  { name: "再见", token: "[再见]", src: "/images/wechat-emoji/035.webp" },
  { name: "擦汗", token: "[擦汗]", src: "/images/wechat-emoji/036.webp" },
  { name: "抠鼻", token: "[抠鼻]", src: "/images/wechat-emoji/037.webp" },
  { name: "鼓掌", token: "[鼓掌]", src: "/images/wechat-emoji/038.webp" },
  { name: "坏笑", token: "[坏笑]", src: "/images/wechat-emoji/039.webp" },
  { name: "右哼哼", token: "[右哼哼]", src: "/images/wechat-emoji/040.webp" },
  { name: "鄙视", token: "[鄙视]", src: "/images/wechat-emoji/041.webp" },
  { name: "委屈", token: "[委屈]", src: "/images/wechat-emoji/042.webp" },
  { name: "快哭了", token: "[快哭了]", src: "/images/wechat-emoji/043.webp" },
  { name: "阴险", token: "[阴险]", src: "/images/wechat-emoji/044.webp" },
  { name: "亲亲", token: "[亲亲]", src: "/images/wechat-emoji/045.webp" },
  { name: "可怜", token: "[可怜]", src: "/images/wechat-emoji/046.webp" },
  { name: "笑脸", token: "[笑脸]", src: "/images/wechat-emoji/047.webp" },
  { name: "生病", token: "[生病]", src: "/images/wechat-emoji/048.webp" },
  { name: "脸红", token: "[脸红]", src: "/images/wechat-emoji/049.webp" },
  { name: "破涕为笑", token: "[破涕为笑]", src: "/images/wechat-emoji/050.webp" },
  { name: "恐惧", token: "[恐惧]", src: "/images/wechat-emoji/051.webp" },
  { name: "失望", token: "[失望]", src: "/images/wechat-emoji/052.webp" },
  { name: "无语", token: "[无语]", src: "/images/wechat-emoji/053.webp" },
  { name: "嘿哈", token: "[嘿哈]", src: "/images/wechat-emoji/054.webp" },
  { name: "捂脸", token: "[捂脸]", src: "/images/wechat-emoji/055.webp" },
  { name: "奸笑", token: "[奸笑]", src: "/images/wechat-emoji/056.webp" },
  { name: "机智", token: "[机智]", src: "/images/wechat-emoji/057.webp" },
  { name: "皱眉", token: "[皱眉]", src: "/images/wechat-emoji/058.webp" },
  { name: "耶", token: "[耶]", src: "/images/wechat-emoji/059.webp" },
  { name: "吃瓜", token: "[吃瓜]", src: "/images/wechat-emoji/060.webp" },
  { name: "加油", token: "[加油]", src: "/images/wechat-emoji/061.webp" },
  { name: "汗", token: "[汗]", src: "/images/wechat-emoji/062.webp" },
  { name: "天啊", token: "[天啊]", src: "/images/wechat-emoji/063.webp" },
  { name: "Emm", token: "[Emm]", src: "/images/wechat-emoji/064.webp" },
  { name: "社会社会", token: "[社会社会]", src: "/images/wechat-emoji/065.webp" },
  { name: "旺柴", token: "[旺柴]", src: "/images/wechat-emoji/066.webp" },
  { name: "好的", token: "[好的]", src: "/images/wechat-emoji/067.webp" },
  { name: "打脸", token: "[打脸]", src: "/images/wechat-emoji/068.webp" },
  { name: "哇", token: "[哇]", src: "/images/wechat-emoji/069.webp" },
  { name: "翻白眼", token: "[翻白眼]", src: "/images/wechat-emoji/070.webp" },
  { name: "666", token: "[666]", src: "/images/wechat-emoji/071.webp" },
  { name: "让我看看", token: "[让我看看]", src: "/images/wechat-emoji/072.webp" },
  { name: "叹气", token: "[叹气]", src: "/images/wechat-emoji/073.webp" },
  { name: "苦涩", token: "[苦涩]", src: "/images/wechat-emoji/074.webp" },
  { name: "裂开", token: "[裂开]", src: "/images/wechat-emoji/075.webp" },
  { name: "嘴唇", token: "[嘴唇]", src: "/images/wechat-emoji/076.webp" },
  { name: "爱心", token: "[爱心]", src: "/images/wechat-emoji/077.webp" },
  { name: "心碎", token: "[心碎]", src: "/images/wechat-emoji/078.webp" },
  { name: "拥抱", token: "[拥抱]", src: "/images/wechat-emoji/079.webp" },
  { name: "强", token: "[强]", src: "/images/wechat-emoji/080.webp" },
  { name: "弱", token: "[弱]", src: "/images/wechat-emoji/081.webp" },
  { name: "握手", token: "[握手]", src: "/images/wechat-emoji/082.webp" },
  { name: "胜利", token: "[胜利]", src: "/images/wechat-emoji/083.webp" },
  { name: "抱拳", token: "[抱拳]", src: "/images/wechat-emoji/084.webp" },
  { name: "勾引", token: "[勾引]", src: "/images/wechat-emoji/085.webp" },
  { name: "拳头", token: "[拳头]", src: "/images/wechat-emoji/086.webp" },
  { name: "OK", token: "[OK]", src: "/images/wechat-emoji/087.webp" },
  { name: "合十", token: "[合十]", src: "/images/wechat-emoji/088.webp" },
  { name: "啤酒", token: "[啤酒]", src: "/images/wechat-emoji/089.webp" },
  { name: "咖啡", token: "[咖啡]", src: "/images/wechat-emoji/090.webp" },
  { name: "蛋糕", token: "[蛋糕]", src: "/images/wechat-emoji/091.webp" },
  { name: "玫瑰", token: "[玫瑰]", src: "/images/wechat-emoji/092.webp" },
  { name: "凋谢", token: "[凋谢]", src: "/images/wechat-emoji/093.webp" },
  { name: "菜刀", token: "[菜刀]", src: "/images/wechat-emoji/094.webp" },
  { name: "炸弹", token: "[炸弹]", src: "/images/wechat-emoji/095.webp" },
  { name: "便便", token: "[便便]", src: "/images/wechat-emoji/096.webp" },
  { name: "月亮", token: "[月亮]", src: "/images/wechat-emoji/097.webp" },
  { name: "太阳", token: "[太阳]", src: "/images/wechat-emoji/098.webp" },
  { name: "庆祝", token: "[庆祝]", src: "/images/wechat-emoji/099.webp" },
  { name: "礼物", token: "[礼物]", src: "/images/wechat-emoji/100.webp" },
  { name: "红包", token: "[红包]", src: "/images/wechat-emoji/101.webp" },
  { name: "發", token: "[發]", src: "/images/wechat-emoji/102.webp" },
  { name: "福", token: "[福]", src: "/images/wechat-emoji/103.webp" },
  { name: "烟花", token: "[烟花]", src: "/images/wechat-emoji/104.webp" },
  { name: "爆竹", token: "[爆竹]", src: "/images/wechat-emoji/105.webp" },
  { name: "猪头", token: "[猪头]", src: "/images/wechat-emoji/106.webp" },
  { name: "跳跳", token: "[跳跳]", src: "/images/wechat-emoji/107.webp" },
  { name: "发抖", token: "[发抖]", src: "/images/wechat-emoji/108.webp" },
  { name: "转圈", token: "[转圈]", src: "/images/wechat-emoji/109.webp" },
];

export const wechatEmojiByToken = new Map(wechatEmojis.map((emoji) => [emoji.token, emoji]));

export function insertWechatEmoji(value: string, token: string, start: number, end = start) {
  const from = Math.max(0, Math.min(start, value.length));
  const to = Math.max(from, Math.min(end, value.length));
  return { value: value.slice(0, from) + token + value.slice(to), caret: from + token.length };
}
