import { expect, test } from "@playwright/test";
import { E2E_ADMIN } from "../seed-data.js";
import type { MessageDTO } from "../../src/shared/types.js";
import type { StoryPageDTO } from "../../src/shared/stories.js";

test("恩典多图 HEIC、编辑与增量故事持久化", async ({ page, request }) => {
  test.setTimeout(120_000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.route("**/*", (route) => ["127.0.0.1", "localhost"].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
  await page.goto("/");
  await page.getByPlaceholder("用户名").fill(E2E_ADMIN.username);
  await page.getByPlaceholder("密码").fill(E2E_ADMIN.password);
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await expect(page.getByTestId("active-channel-name")).toBeVisible();
  const token = await page.evaluate(() => localStorage.getItem("team-chat-token"));
  const headers = { Authorization: `Bearer ${token}` };
  const me = (await (await request.get("/api/auth/me", { headers })).json()).account;
  await page.getByRole("button", { name: "更多功能" }).click();
  await page.getByRole("button", { name: "数算恩典", exact: true }).click();
  const composer = page.getByRole("dialog", { name: "记录恩典", exact: true });
  const content = "恩典多图回归：今天一路平安";
  await composer.locator("textarea").fill(content);
  await composer.getByLabel("添加恩典照片").setInputFiles(["e2e/fixtures/story-sample.heic", "public/images/stories/story-banner.png"]);
  await expect(composer.locator(".grace-photo-chip")).toHaveCount(2);
  await expect.poll(() => composer.locator(".grace-photo-chip img").first().evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBeTruthy();
  const createdResponse = page.waitForResponse((response) => response.url().endsWith("/api/grace") && response.request().method() === "POST");
  await composer.getByRole("button", { name: "存入恩典册" }).click();
  const created = (await (await createdResponse).json()).message as MessageDTO;
  await expect(composer).toBeHidden();
  const card = page.locator(`[data-message-id="${created.id}"] .grace-card`);
  await expect(card.locator(".grace-photo-grid img")).toHaveCount(2);
  const initialStories = await (await request.get(`/api/stories?actorId=${me.actorId}`, { headers })).json() as StoryPageDTO;
  expect(initialStories.stories[0].text).toBe(content);
  expect(initialStories.stories[0].media).toHaveLength(2);
  const images = (created.payload as { images: Array<{ fileName: string }> }).images;
  const imageUrl = `/api/grace/${created.id}/images/${images[0].fileName}`;
  expect((await request.get(imageUrl, { headers })).status()).toBe(200);
  expect((await request.get(imageUrl)).status()).toBe(401);

  await card.getByRole("button", { name: "编辑卡片" }).click();
  const editor = page.getByRole("dialog", { name: "编辑恩典卡片", exact: true });
  await expect(editor.getByLabel("恩典内容")).toHaveValue(content);
  await expect(editor.locator(".grace-photo-chip")).toHaveCount(2);
  for (const width of [360, 390, 1280]) {
    await page.setViewportSize({ width, height: 900 });
    await expect(editor.getByRole("button", { name: "关闭恩典见证编辑" })).toBeVisible();
    expect(await editor.locator(".grace-composer-modal").evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBeTruthy();
  }
  await editor.getByRole("button", { name: "移除原有照片 1", exact: true }).click();
  await editor.getByLabel("添加恩典照片").setInputFiles("public/images/stories/story-banner.png");
  await expect(editor.locator(".grace-photo-chip")).toHaveCount(2);
  await editor.getByLabel("恩典内容").fill(`${content}\n后来收到新的帮助`);
  const updatedResponse = page.waitForResponse((response) => response.url().endsWith(`/api/messages/${created.id}/grace-update`) && response.request().method() === "POST");
  await editor.getByRole("button", { name: "保存并同步故事" }).click();
  const updated = (await (await updatedResponse).json()).message as MessageDTO;
  await expect(editor).toBeHidden();
  const stories = await (await request.get(`/api/stories?actorId=${me.actorId}`, { headers })).json() as StoryPageDTO;
  expect(stories.stories[0].text).toBe("恩典更新：\n后来收到新的帮助");
  expect(stories.stories[0].media).toHaveLength(1);
  expect(stories.stories[1].id).toBe(initialStories.stories[0].id);
  expect(stories.stories[1].media).toHaveLength(2);
  const timeline = (await (await request.get(`/api/messages?channelId=${created.channelId}&after=${created.id - 1}`, { headers })).json()).messages as MessageDTO[];
  expect(timeline.filter((message) => message.id >= created.id).map((message) => message.type)).toEqual(["grace", "grace"]);
  await page.reload();
  const persisted = page.locator(`[data-message-id="${updated.id}"] .grace-card`);
  await expect(persisted.locator(".grace-card-text").first()).toContainText("后来收到新的帮助");
  await expect(persisted.locator(".grace-photo-grid").first().locator("img")).toHaveCount(2);
  expect(errors).toEqual([]);
});
