-- AlterTable
ALTER TABLE `accounts` ADD COLUMN `story_feed_read_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `story_interaction_read_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
