const rangeToken = String.raw`\s*(?:-|－|–|—|―|﹣|～|~|到|至)\s*`;

const bibleBookAliases = [
  "创世记",
  "创世纪",
  "创",
  "Genesis",
  "Gen",
  "Ge",
  "Gn",
  "出埃及记",
  "出",
  "Exodus",
  "Exod",
  "Exo",
  "Ex",
  "利未记",
  "利",
  "Leviticus",
  "Lev",
  "Le",
  "民数记",
  "民",
  "Numbers",
  "Num",
  "Nu",
  "Nm",
  "申命记",
  "申",
  "Deuteronomy",
  "Deut",
  "Deu",
  "Dt",
  "约书亚记",
  "书",
  "Joshua",
  "Josh",
  "Jos",
  "士师记",
  "士",
  "Judges",
  "Judg",
  "Jdg",
  "路得记",
  "得",
  "Ruth",
  "Rut",
  "Ru",
  "撒母耳记上",
  "撒母耳上",
  "撒上",
  "1 Samuel",
  "1Samuel",
  "1 Sam",
  "1Sam",
  "撒母耳记下",
  "撒母耳下",
  "撒下",
  "2 Samuel",
  "2Samuel",
  "2 Sam",
  "2Sam",
  "列王纪上",
  "王上",
  "1 Kings",
  "1Kings",
  "列王纪下",
  "王下",
  "2 Kings",
  "2Kings",
  "历代志上",
  "代上",
  "1 Chronicles",
  "1Chronicles",
  "1 Chron",
  "1Chron",
  "历代志下",
  "代下",
  "2 Chronicles",
  "2Chronicles",
  "2 Chron",
  "2Chron",
  "以斯拉记",
  "拉",
  "Ezra",
  "Ezr",
  "尼希米记",
  "尼",
  "Nehemiah",
  "Neh",
  "以斯帖记",
  "斯",
  "Esther",
  "Est",
  "约伯记",
  "伯",
  "Job",
  "Jb",
  "诗篇",
  "诗",
  "Psalms",
  "Psalm",
  "Ps",
  "Psa",
  "箴言",
  "箴",
  "Proverbs",
  "Prov",
  "Pro",
  "Pr",
  "传道书",
  "传",
  "Ecclesiastes",
  "Eccl",
  "Ecc",
  "雅歌",
  "歌",
  "Song of Songs",
  "SongofSongs",
  "Song",
  "Songs",
  "Song of Solomon",
  "以赛亚书",
  "赛",
  "Isaiah",
  "Isa",
  "耶利米书",
  "耶",
  "Jeremiah",
  "Jer",
  "耶利米哀歌",
  "哀",
  "Lamentations",
  "Lam",
  "以西结书",
  "结",
  "Ezekiel",
  "Ezek",
  "但以理书",
  "但",
  "Daniel",
  "Dan",
  "何西阿书",
  "何",
  "Hosea",
  "Hos",
  "约珥书",
  "珥",
  "Joel",
  "阿摩司书",
  "摩",
  "Amos",
  "俄巴底亚书",
  "俄",
  "Obadiah",
  "约拿书",
  "拿",
  "Jonah",
  "Jon",
  "弥迦书",
  "弥",
  "Micah",
  "Mic",
  "那鸿书",
  "鸿",
  "Nahum",
  "Nah",
  "哈巴谷书",
  "哈",
  "Habakkuk",
  "Hab",
  "西番雅书",
  "番",
  "Zephaniah",
  "Zeph",
  "哈该书",
  "该",
  "Haggai",
  "Hag",
  "撒迦利亚书",
  "亚",
  "Zechariah",
  "Zech",
  "玛拉基书",
  "玛",
  "Malachi",
  "Mal",
  "马太福音",
  "马太",
  "太",
  "Matthew",
  "Matt",
  "Mt",
  "马可福音",
  "马可",
  "可",
  "Mark",
  "Mk",
  "路加福音",
  "路加",
  "路",
  "Luke",
  "Lk",
  "约翰福音",
  "约翰",
  "约",
  "John",
  "Jn",
  "使徒行传",
  "徒",
  "Acts",
  "Act",
  "罗马书",
  "罗",
  "Romans",
  "Rom",
  "哥林多前书",
  "林前",
  "1 Corinthians",
  "1Corinthians",
  "1 Cor",
  "1Cor",
  "哥林多后书",
  "林后",
  "2 Corinthians",
  "2Corinthians",
  "2 Cor",
  "2Cor",
  "加拉太书",
  "加",
  "Galatians",
  "Gal",
  "以弗所书",
  "弗",
  "Ephesians",
  "Eph",
  "腓立比书",
  "腓",
  "Philippians",
  "Phil",
  "歌罗西书",
  "西",
  "Colossians",
  "Col",
  "帖撒罗尼迦前书",
  "帖前",
  "1 Thessalonians",
  "1Thessalonians",
  "1 Thess",
  "1Thess",
  "帖撒罗尼迦后书",
  "帖后",
  "2 Thessalonians",
  "2Thessalonians",
  "2 Thess",
  "2Thess",
  "提摩太前书",
  "提前",
  "1 Timothy",
  "1Timothy",
  "1 Tim",
  "1Tim",
  "提摩太后书",
  "提后",
  "2 Timothy",
  "2Timothy",
  "2 Tim",
  "2Tim",
  "提多书",
  "多",
  "Titus",
  "Tit",
  "腓利门书",
  "门",
  "Philemon",
  "Phm",
  "希伯来书",
  "来",
  "Hebrews",
  "Heb",
  "雅各书",
  "雅",
  "James",
  "Jas",
  "彼得前书",
  "彼前",
  "1 Peter",
  "1Peter",
  "1 Pet",
  "1Pet",
  "彼得后书",
  "彼后",
  "2 Peter",
  "2Peter",
  "2 Pet",
  "2Pet",
  "约翰一书",
  "约一",
  "1 John",
  "1John",
  "1 Jn",
  "1Jn",
  "约翰二书",
  "约二",
  "2 John",
  "2John",
  "2 Jn",
  "2Jn",
  "约翰三书",
  "约三",
  "3 John",
  "3John",
  "3 Jn",
  "3Jn",
  "犹大书",
  "犹",
  "Jude",
  "Jud",
  "启示录",
  "启",
  "Revelation",
  "Revelations",
  "Rev"
];

const aliasPattern = bibleBookAliases
  .map((alias) => alias.trim())
  .filter(Boolean)
  .sort((left, right) => right.length - left.length)
  .map(escapeRegExp)
  .join("|");
const sortedAliases = bibleBookAliases
  .map((alias) => alias.trim())
  .filter(Boolean)
  .sort((left, right) => right.length - left.length);

const colonStyle = String.raw`\d+\s*[:：]\s*\d+(?:${rangeToken}(?:\d+\s*[:：]\s*)?\d+)?`;
const chapterStyle = String.raw`第?\s*\d+\s*章(?:\s*第?\s*\d+(?:${rangeToken}\d+)?\s*节?)?`;
const wholeChapterStyle = String.raw`\d+`;
const referencePattern = new RegExp(String.raw`(^|[^A-Za-z0-9])((?:${aliasPattern})\s*(?:${colonStyle}|${chapterStyle}|${wholeChapterStyle}))(?=$|[^A-Za-z0-9])`, "giu");

export function extractBibleReferencesFromText(text: string, max = 8) {
  const references: string[] = [];
  const seen = new Set<string>();
  for (const match of text.matchAll(referencePattern)) {
    const reference = cleanReferenceCandidate(match[2] || "");
    const key = reference.toLowerCase().replace(/\s+/g, "");
    if (!reference || isRiskySingleCharacterChapter(reference) || seen.has(key)) continue;
    seen.add(key);
    references.push(reference);
    if (references.length >= max) break;
  }
  return references;
}

function cleanReferenceCandidate(reference: string) {
  return reference
    .replace(/\s*([:：])\s*/g, "$1")
    .replace(/\s+/g, " ")
    .trim();
}

function isRiskySingleCharacterChapter(reference: string) {
  if (/[:：章节]/.test(reference)) return false;
  const compactReference = reference.toLowerCase().replace(/\s+/g, "");
  for (const alias of sortedAliases) {
    const compactAlias = alias.toLowerCase().replace(/\s+/g, "");
    if (!compactReference.startsWith(compactAlias)) continue;
    const body = compactReference.slice(compactAlias.length);
    return /^[\u4e00-\u9fff]$/.test(alias) && /^\d+$/.test(body);
  }
  return false;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
